### ISSUE TITLE
parameters not updating after making changes to the config file 

### ISSUE THREAD

**Issue by rshah18** [aws-robotics/lex-ros1#26]
parameters not updating after making changes to the config file

**Comment by AAlon** [comment]
Hi @rshah18, could you please provide steps to reproduce the issue? 
Just to clarify, the node does not support dynamic reconfigure. If you don't restart the node you won't be able to change the parameters.

**Comment by rshah18** [comment]
I had two different sets of same package installed. I resolved the issue. thank you so much for replying.

**Comment by AAlon** [comment]
Glad you were able to get it working! I'll go ahead and close this then, let us know in case of any other questions.
